import { Geist, Geist_Mono ,Dancing_Script } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import AllergyWarningCard from "./components/AllergyWarningCard";
import WhatsAppButton from "./components/WhatsAppButton";
import Footer from "./Sections/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dancingScript = Dancing_Script({
  variable: "--font-dancing-script",
  subsets: ["latin"],
});

export const metadata = {
  title: "Relaxing Foods",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dancingScript.variable} antialiased overflow-x-hidden`}
      >
        <Navbar />
        {children}
        <AllergyWarningCard />
        <WhatsAppButton />
        <Footer />
      </body>
    </html>
  );
}
